# Generated by Django 5.0.3 on 2024-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_api', '0003_wallet_transaction_delete_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
