# Generated by Django 5.0.3 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_api', '0004_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
